name: CD backend

on:
  # push:
  #   branches:
  #     - release
  workflow_run:
    workflows: ["CI Backend"]
    types:
      - completed

jobs:
  deploy:
    # Solo correr si el CI terminó en success
    # y la rama que se analizó es 'release'
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'release' }}
    runs-on: ubuntu-latest
    #runs-on: ubuntu-latest
    env:
      SVC_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Build project
        run: |
          npm ci
          npm run build

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        run: railway up --service=${{ env.SVC_ID }}
